### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by Xapitonov**

### CODE REVIEW

**Comment by lemenkov** [comment]
Thank you for the PR. I've added comments but it's a good starting point!

**Comment by lemenkov** [comment]
Btw I'd either split this PR into two different ones (let's start with ru.pot first) and later added squashed commit related to po/LINGUAS.

**Comment by lemenkov** [comment]
Ok we need to rebase that one :)
@domichel

**Comment by domichel** [comment]
Thanks!
commit 7a32bda fix it.

**Comment by Xapitonov** [comment]
Hi! 🤝

Transferred file to zip.

Google spreadsheet app or website!

=======

**Translation Hint**

We need to add all the projects
to the translation service.

_For example _

Weblate: https://weblate.org/
Crowdin: https://crowdin.com/
or others of your choice.

It will be faster, better, more efficient!

**Icons (signs)**

Free icon creation with AI
https://www.yeschat.ai/ru/gpts-2OToEofjtR-3d-Icon-generator
Or others .

Good Luck Brother, Friend! 😜


вт, 27 авг. 2024 г., 18:03 Dominique Michel ***@***.***>:

**Pull request closed without merging**
